### ISSUE TITLE
Error while running npm start

### ISSUE THREAD

**Issue by maektwain** [lastfermat-s/provably-fair-project#1]
> provably-fair-project@0.1.0 start /Users/xxx/provably-fair-project
> node scripts/start.js "dev"

Cannot read property 'entryOption' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! provably-fair-project@0.1.0 start: `node scripts/start.js "dev"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the provably-fair-project@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2019-08-25T13_03_11_833Z-debug.log

**Comment by Devilla** [comment]
Fixed.
