### ISSUE TITLE
Separate and structure components for each casino.

### ISSUE THREAD

**Issue by Devilla** [lastfermat-s/provably-fair-project#18]
Now, there's only a single component handeling all the casinos. Try restructuring and separate these into multiple reusable components for `App.js` and `content.js `(Chrome Extention).
[. ] Separate components for every operator.
[. ] Pass data through store/props
[. ] Communicate b/w components and methods

**Comment by qwaser109** [comment]
Hey Devilla. I notice you are still working on my extension. How can I help? If you want to continue where we left off without any middlemen controlling your money, hit me up on Telegram. I can fund this tool to completion.

**Comment by Devilla** [comment]
Sounds good. Thanks.

**Comment by Devilla** [comment]
Solved https://github.com/provably-fair/provably-fair-app/pull/24
