### ISSUE TITLE
handling rate limits

### ISSUE THREAD

**Issue by livingrock7** [lastfermat-s/provably-fair-project#2]
our major blocker with bitvest running into 503 errors followed by 403.

here's some references 

https://hackernoon.com/limiting-your-api-requests-the-right-way-9608b661a0ce

**Comment by livingrock7** [comment]
https://github.com/axios/axios/issues/934

**Comment by livingrock7** [comment]
https://github.com/axios/axios/issues/960

**Comment by Devilla** [comment]
Done.
