### ISSUE TITLE
Add support for bc.game

### ISSUE THREAD

**Issue by Devilla** [lastfermat-s/provably-fair-project#31]
Reference : 

- https://provably-fair.github.io/bcgame/

- https://github.com/provably-fair/bcgame

- https://bc.game/home

- https://forum.bc.game/topic/2442-community-verification-toolsscripts-competition/?tab=comments#comment-10953

**Comment by kutu-loncat** [comment]
Sever

10991ccec4bf0e898806846abd5f1e9118c386cf1ce111ca3423029c91738ba6

Benih:

eefec4ca0ee62668e24aff1bd024e4a985fe642c256676355cae44776b6dfcb7

Hentikan:

18942090


Benih clien :

0x6aa664e95e77989d0ef213f235b4e650ad94da519529ea91378da807b694d77f

**Comment by Devilla** [comment]
> Sever
> 
> 10991ccec4bf0e898806846abd5f1e9118c386cf1ce111ca3423029c91738ba6
> 
> Benih:
> 
> eefec4ca0ee62668e24aff1bd024e4a985fe642c256676355cae44776b6dfcb7
> 
> Hentikan:
> 
> 18942090
> 
> Benih clien :
> 
> 0x6aa664e95e77989d0ef213f235b4e650ad94da519529ea91378da807b694d77f

Which game are you willing to verify?

**Comment by kutu-loncat** [comment]
The Lottery

Pada Jum, 26 Jan 2024 00.42, Devendra Yadav ***@***.***>
menulis:

**Comment by Devilla** [comment]
![Screenshot_20240125-233639](https://github.com/provably-fair/provably-fair-app/assets/15603274/87bd3b5d-deb6-4cdf-bb7f-2e97f850dc1c)
Only these are the currently supported games.

**Comment by kutu-loncat** [comment]
The Lottery.html

**Comment by kutu-loncat** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lottery verify</title>
  <link rel="stylesheet" href="./lib/main.css">
  <link rel="stylesheet" href="./lib/bootstrap/css/bootstrap.min.css">
  <script src="./lib/react.production.min.js"></script>
  <script src="./lib/react-dom.production.min.js"></script>
  <script src="./lib/crypto-js.js"></script>
  <script src="./lib/tools.js"></script>
  <script src="./lib/hooks.js"></script>
  <script src="./lib/babel.min.js"></script>
</head>
<body>
  <div id="app"></div>
  <script type="text/babel">
    let qs = tools.queryString();
    let { useEffect, useMemo } = React;
    const { useSetState } = hooks;
    function useInputControl (initState) {
      const [state, setState] = useSetState(initState);
      const bind = key => ({
        value: state[key],
        onChange: v => setState({[key]: v})
      });
      return [
        state,
        setState,
        bind
      ];
    }
    function Input ({value, onChange, ...others}) {
      return (
        <div class="form-group">
          <input value={value}
            onChange={e => onChange(e.target.value)}
            class="form-control"
            {...others}
          />
        </div>
      );
    }

    function getRandomByHash (hash) {
      return hash.match(/.{2}/g)
        .map(it => parseInt(it, 16))
        .reduce((res, it, i) => res + it/(256**(i+1)), 0);
    }

    function getBalls (hash) {
      const remainingBalls = Array(36).fill(null).map((v, i) => i+1);
      const balls = [];
      for (let i=0; i<5; i++) {
        const random = getRandomByHash(hash.substr(i*8, 8));
        const ballIndex = Math.floor(random*remainingBalls.length);

        balls.push(remainingBalls.splice(ballIndex, 1)[0]);
      }
      const jackpot = Math.floor(getRandomByHash(hash.substr(5*8, 8)) * 10)+1;
      return balls.concat(jackpot);
    }
    function Lottery () {
      const [state, setState, bind] = useInputControl({
        clientSeed: qs.c||'',
        serverSeed: qs.s||'',
      });

      const result = useMemo(() => {
        const serverSeedHash = tools.sha256(state.serverSeed);
        const hash = String(CryptoJS.HmacSHA256(state.clientSeed, state.serverSeed));
        const balls = getBalls(hash);
        const numbers = balls.slice(0, 5);
        const jackpot = balls[5];
        return {
          serverSeedHash,
          hash,
          numbers,
          jackpot,
        }
      }, [state]);

      return (
        <div className="main">
          <h1 className="text-center pb-5">Lottery verify</h1> 
          <hr />
          <h2 class="text-center">Input</h2>
          <form className="py-5">
            <Input placeholder="Server Seed" {...bind('serverSeed')} />
            <Input placeholder="Client Seed (Hashed)" {...bind('clientSeed')} />
          </form>
          <h2 class="text-center">Output</h2>
          <form className="py-5">
            <Input placeholder="HmacSHA256(clientSeed, serverSeed)" readOnly value={result.hash} />
            <Input placeholder="Numbers" readOnly value={result.numbers.join(', ')} />
            <Input placeholder="Jackpot" readOnly value={result.jackpot} />
          </form>
        </div>
      );
    }
    ReactDOM.render(<Lottery />, document.getElementById("app"));
  </script>
</body>
</html>
